/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.BazaKarta;
import backend.KartaDostepowa;
import backend.Pracownik;
import backend.RodzajKarty;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Piotr Buczek
 */
public class KartyDostepoweFrame extends javax.swing.JFrame {

    /**
     * Creates new form KartyDostepoweFrame
     */
    public KartyDostepoweFrame() {
        initComponents();
        this.zablokujTekst();
        bd = new BazaKarta();
        dane = bd.odczyt();
        pf = new PracownikFrame();
        kartyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        kartyComboBox.addActionListener(new ActionListener() {
 
        @Override
        public void actionPerformed(ActionEvent event) {
        JComboBox<String> combo = (JComboBox<String>) event.getSource();
        String selectedKarta = (String) combo.getSelectedItem();
 
        wyswietlKarte(Integer.parseInt(selectedKarta));
            }
        });
        
        this.bZapisz.setEnabled(false);
        this.wyswietl(0);
        this.setTitle("Menedżer kart dostępowych");
    }
    
    private void wyswietl(int i){
        KartaDostepowa k = dane.get(i);
        tNumerKarty.setText(""+k.getNrKarty());
        rodzajeComboBox.setSelectedItem(k.getRodzajKarty().toString());
        tDataWykupienia.setText(k.getDataWykupienia());
        tDataZakonczenia.setText(k.getDataZakonczenia());
        tNrPracownika.setText(""+k.getNrPracownika());
    }
    
    private void wyswietlKarte(int nrKarty){
        for(int i=0;i<dane.size();i++){
            if(((KartaDostepowa)dane.get(i)).getNrKarty()==nrKarty){
                this.i = i;
                wyswietl(i);
            }
        }
    }

    private String[] initializeComboBox(ArrayList<KartaDostepowa> karty){
        String[] numbers = new String[karty.size()];
        int i = 0;
        for(KartaDostepowa karta : karty){
            numbers[i] = String.valueOf(karta.getNrKarty());
            i++;
        }
        return numbers;
    }
    
    private void odblokujTekst(){
        tNumerKarty.setEnabled(true);
        rodzajeComboBox.setEnabled(true);
        tNrPracownika.setEnabled(true);
        tDataZakonczenia.setEnabled(true);
        tDataWykupienia.setEnabled(true);
    }
    
    private void zablokujTekst(){
        tNumerKarty.setEnabled(false);
        rodzajeComboBox.setEnabled(false);
        tNrPracownika.setEnabled(false);
        tDataZakonczenia.setEnabled(false);
        tDataWykupienia.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kartyComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNumerKarty = new javax.swing.JTextField();
        tDataWykupienia = new javax.swing.JTextField();
        tDataZakonczenia = new javax.swing.JTextField();
        tNrPracownika = new javax.swing.JTextField();
        bNowy = new javax.swing.JButton();
        bZapisz = new javax.swing.JButton();
        bEdytuj = new javax.swing.JButton();
        bUsun = new javax.swing.JButton();
        bWyswietl = new javax.swing.JButton();
        rodzajeComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mNowy = new javax.swing.JMenuItem();
        mZapisz = new javax.swing.JMenuItem();
        mKoniec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mEdytuj = new javax.swing.JMenuItem();
        mUsun = new javax.swing.JMenuItem();

        jLabel1.setText("Wybierz numer karty:");

        kartyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Numer karty:");

        jLabel3.setText("Rodzaj karty:");

        jLabel4.setText("Data wykupienia:");

        jLabel5.setText("Data zakończenia:");

        jLabel6.setText("Numer pracownika:");

        tNumerKarty.setText("jTextField1");

        tDataWykupienia.setText("jTextField3");

        tDataZakonczenia.setText("jTextField4");

        tNrPracownika.setText("jTextField5");

        bNowy.setText("Nowa");
        bNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNowyActionPerformed(evt);
            }
        });

        bZapisz.setText("Zapisz");
        bZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZapiszActionPerformed(evt);
            }
        });

        bEdytuj.setText("Edytuj");
        bEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEdytujActionPerformed(evt);
            }
        });

        bUsun.setText("Usuń");
        bUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsunActionPerformed(evt);
            }
        });

        bWyswietl.setText("Wyświetl dane o pracowniku");
        bWyswietl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWyswietlActionPerformed(evt);
            }
        });

        rodzajeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "biuro", "parking", "łączona" }));

        jMenu1.setText("Plik");

        mNowy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNowy.setText("Nowy");
        mNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNowyActionPerformed(evt);
            }
        });
        jMenu1.add(mNowy);

        mZapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mZapisz.setText("Zapisz");
        mZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mZapiszActionPerformed(evt);
            }
        });
        jMenu1.add(mZapisz);

        mKoniec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mKoniec.setText("Koniec");
        mKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKoniecActionPerformed(evt);
            }
        });
        jMenu1.add(mKoniec);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edycja");

        mEdytuj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mEdytuj.setText("Edytuj");
        mEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEdytujActionPerformed(evt);
            }
        });
        jMenu2.add(mEdytuj);

        mUsun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mUsun.setText("Usuń");
        mUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsunActionPerformed(evt);
            }
        });
        jMenu2.add(mUsun);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bNowy)
                                .addGap(18, 18, 18)
                                .addComponent(bZapisz)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kartyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(bEdytuj)
                                .addGap(30, 30, 30)
                                .addComponent(bUsun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNumerKarty)
                            .addComponent(tDataWykupienia)
                            .addComponent(tDataZakonczenia)
                            .addComponent(tNrPracownika)
                            .addComponent(rodzajeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(bWyswietl)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kartyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNumerKarty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rodzajeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tDataWykupienia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tDataZakonczenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tNrPracownika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bWyswietl)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNowy)
                    .addComponent(bZapisz)
                    .addComponent(bEdytuj)
                    .addComponent(bUsun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNowyActionPerformed
        // TODO add your handling code here:
        this.odblokujTekst();
        this.bNowy.setEnabled(false);
        this.bZapisz.setEnabled(true);
        this.bEdytuj.setEnabled(false);
        this.bUsun.setEnabled(false);
         this.bWyswietl.setEnabled(false);

        kartyComboBox.setEnabled(false);
        tNrPracownika.setText("");       
        tDataZakonczenia.setText("");
        tDataWykupienia.setText("");
        tNumerKarty.setText("");
    }//GEN-LAST:event_bNowyActionPerformed

    private void bZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZapiszActionPerformed
        // TODO add your handling code here:
        if(tNumerKarty.isEnabled()){
            bd.zapis(tNumerKarty.getText(),
                    RodzajKarty.valueOf(rodzajeComboBox.getSelectedItem().toString()),
           tDataWykupienia.getText(),
        tDataZakonczenia.getText(),
        tNrPracownika.getText());
        } else if(!tNumerKarty.isEnabled()){
            bd.modyfikuj(tNumerKarty.getText(),
                    RodzajKarty.valueOf(rodzajeComboBox.getSelectedItem().toString()),
           tDataWykupienia.getText(),
        tDataZakonczenia.getText(),
        tNrPracownika.getText());
        }
        this.zablokujTekst();
        this.bNowy.setEnabled(true);
        this.bZapisz.setEnabled(false);
        this.bEdytuj.setEnabled(true);
        this.bUsun.setEnabled(true);
        this.bWyswietl.setEnabled(true);
        kartyComboBox.setEnabled(true);
        dane = bd.odczyt();
        kartyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        kartyComboBox.setSelectedItem(tNumerKarty.getText());
    }//GEN-LAST:event_bZapiszActionPerformed

    private void bEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEdytujActionPerformed
        // TODO add your handling code here:
        this.odblokujTekst();
        kartyComboBox.setEnabled(false);
        this.tNumerKarty.setEnabled(false);
        this.bZapisz.setEnabled(true);
        this.bNowy.setEnabled(false);
        this.bUsun.setEnabled(false);
        this.bEdytuj.setEnabled(false);
    }//GEN-LAST:event_bEdytujActionPerformed

    private void bUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsunActionPerformed
        // TODO add your handling code here:
        bd.usun(tNumerKarty.getText());
        dane = bd.odczyt();
        kartyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        kartyComboBox.setSelectedItem(String.valueOf(dane.get(0).getNrKarty()));
    }//GEN-LAST:event_bUsunActionPerformed

    private void bWyswietlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWyswietlActionPerformed
        // TODO add your handling code here:
        pf.wyswietlPracownika(Long.parseLong(tNrPracownika.getText()));
        pf.setVisible(true);
    }//GEN-LAST:event_bWyswietlActionPerformed

    private void mNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNowyActionPerformed
        // TODO add your handling code here:
        this.bNowyActionPerformed(evt);
    }//GEN-LAST:event_mNowyActionPerformed

    private void mZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mZapiszActionPerformed
        // TODO add your handling code here:
        this.bZapiszActionPerformed(evt);
    }//GEN-LAST:event_mZapiszActionPerformed

    private void mKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKoniecActionPerformed
        // TODO add your handling code here:
        dispose();
        setVisible(false);
    }//GEN-LAST:event_mKoniecActionPerformed

    private void mEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEdytujActionPerformed
        // TODO add your handling code here:
        this.bEdytujActionPerformed(evt);
    }//GEN-LAST:event_mEdytujActionPerformed

    private void mUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsunActionPerformed
        // TODO add your handling code here:
        this.bUsunActionPerformed(evt);
    }//GEN-LAST:event_mUsunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KartyDostepoweFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KartyDostepoweFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KartyDostepoweFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KartyDostepoweFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KartyDostepoweFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdytuj;
    private javax.swing.JButton bNowy;
    private javax.swing.JButton bUsun;
    private javax.swing.JButton bWyswietl;
    private javax.swing.JButton bZapisz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> kartyComboBox;
    private javax.swing.JMenuItem mEdytuj;
    private javax.swing.JMenuItem mKoniec;
    private javax.swing.JMenuItem mNowy;
    private javax.swing.JMenuItem mUsun;
    private javax.swing.JMenuItem mZapisz;
    private javax.swing.JComboBox<String> rodzajeComboBox;
    private javax.swing.JTextField tDataWykupienia;
    private javax.swing.JTextField tDataZakonczenia;
    private javax.swing.JTextField tNrPracownika;
    private javax.swing.JTextField tNumerKarty;
    // End of variables declaration//GEN-END:variables
    private BazaKarta bd;
    private ArrayList<KartaDostepowa> dane;
    private int i;
    private PracownikFrame pf;
}
