/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.BazaPracownik;
import backend.Pracownik;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Piotr Buczek
 */
public class PracownikFrame extends javax.swing.JFrame {

    /**
     * Creates new form PracownikFrame
     */
    public PracownikFrame() {
        initComponents();
        zablokujTekst();
        bd = new BazaPracownik();
        dane = bd.odczyt();
        pracownicyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        pracownicyComboBox.addActionListener(new ActionListener() {
 
        @Override
        public void actionPerformed(ActionEvent event) {
        JComboBox<String> combo = (JComboBox<String>) event.getSource();
        String selectedPracownik = (String) combo.getSelectedItem();
 
        wyswietlPracownika(Long.parseLong(selectedPracownik));
            }
        });
        
        this.bZapisz.setEnabled(false);
        this.wyswietl(0);
        this.setTitle("Menedżer pracowników");
    }
    
    private void wyswietl(int i){
        Pracownik p = dane.get(i);
        tNrPracownika.setText(""+p.getNrPracownika());
        tImie.setText(p.getImie());
        tNazwisko.setText(p.getNazwisko());
        tNumerTelefonu.setText(""+p.getNumerTelefonu());
        tMiejscowosc.setText(p.getMiejscowosc());
        tKodpocztowy.setText(p.getKodPocztowy());
        tUlica.setText(p.getUlica());
        tStanowisko.setText(p.getStanowisko());
        tDataRozpoczecia.setText(p.getDataRozpoczeniaPracy());        
        tDataZakonczenia.setText(p.getDataZakonczeniaPracy());

    }
    
    public void wyswietlPracownika(long nrPracownika){
        for(int i=0;i<dane.size();i++){
            if(((Pracownik)dane.get(i)).getNrPracownika()==nrPracownika){
                this.i = i;
                wyswietl(i);
                pracownicyComboBox.setSelectedItem(String.valueOf(nrPracownika));
            }
        }
    }
    
    private String[] initializeComboBox(ArrayList<Pracownik> pracownicy){
        String[] numbers = new String[pracownicy.size()];
        int i = 0;
        for(Pracownik pracownik : pracownicy){
            numbers[i] = String.valueOf(pracownik.getNrPracownika());
            i++;
        }
        return numbers;
    }
    
    private void odblokujTekst(){
        tNrPracownika.setEnabled(true);
        tImie.setEnabled(true);
        tNazwisko.setEnabled(true);
        tNumerTelefonu.setEnabled(true);
        tMiejscowosc.setEnabled(true);
        tKodpocztowy.setEnabled(true);
        tUlica.setEnabled(true);
        tStanowisko.setEnabled(true);
        tDataRozpoczecia.setEnabled(true);
        tDataZakonczenia.setEnabled(true);
    }
    
    private void zablokujTekst(){
        tNrPracownika.setEnabled(false);
        tImie.setEnabled(false);
        tNazwisko.setEnabled(false);
        tNumerTelefonu.setEnabled(false);
        tMiejscowosc.setEnabled(false);
        tKodpocztowy.setEnabled(false);
        tUlica.setEnabled(false);
        tStanowisko.setEnabled(false);
        tDataRozpoczecia.setEnabled(false);
        tDataZakonczenia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pracownicyComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tImie = new javax.swing.JTextField();
        tNazwisko = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tNumerTelefonu = new javax.swing.JTextField();
        tMiejscowosc = new javax.swing.JTextField();
        tKodpocztowy = new javax.swing.JTextField();
        tUlica = new javax.swing.JTextField();
        tStanowisko = new javax.swing.JTextField();
        tDataRozpoczecia = new javax.swing.JTextField();
        tDataZakonczenia = new javax.swing.JTextField();
        bNowy = new javax.swing.JButton();
        bEdytuj = new javax.swing.JButton();
        bUsun = new javax.swing.JButton();
        bZapisz = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tNrPracownika = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mNowy = new javax.swing.JMenuItem();
        mZapisz = new javax.swing.JMenuItem();
        mKoniec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mEdytuj = new javax.swing.JMenuItem();
        mUsun = new javax.swing.JMenuItem();

        pracownicyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pracownicyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracownicyComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Wybierz numer pracownika:");

        tImie.setText("jTextField1");

        tNazwisko.setText("jTextField2");

        jLabel2.setText("Imie:");

        jLabel3.setText("Nazwisko:");

        jLabel4.setText("Numer telefonu:");

        jLabel5.setText("Miejscowość:");

        jLabel6.setText("Kod pocztowy:");

        jLabel7.setText("Ulica:");

        jLabel8.setText("Stanowisko:");

        jLabel9.setText("Data rozpoczęcia pracy:");

        jLabel10.setText("Data zakończenia pracy:");

        tNumerTelefonu.setText("jTextField3");

        tMiejscowosc.setText("jTextField4");

        tKodpocztowy.setText("jTextField5");

        tUlica.setText("jTextField6");

        tStanowisko.setText("jTextField7");

        tDataRozpoczecia.setText("jTextField8");

        tDataZakonczenia.setText("jTextField9");

        bNowy.setText("Nowy");
        bNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNowyActionPerformed(evt);
            }
        });

        bEdytuj.setText("Edytuj");
        bEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEdytujActionPerformed(evt);
            }
        });

        bUsun.setText("Usuń");
        bUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsunActionPerformed(evt);
            }
        });

        bZapisz.setText("Zapisz");
        bZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZapiszActionPerformed(evt);
            }
        });

        jLabel11.setText("Numer pracownika:");

        tNrPracownika.setText("jTextField1");

        jMenu1.setText("Plik");

        mNowy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNowy.setText("Nowy");
        mNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNowyActionPerformed(evt);
            }
        });
        jMenu1.add(mNowy);

        mZapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mZapisz.setText("Zapisz");
        mZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mZapiszActionPerformed(evt);
            }
        });
        jMenu1.add(mZapisz);

        mKoniec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mKoniec.setText("Koniec");
        mKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKoniecActionPerformed(evt);
            }
        });
        jMenu1.add(mKoniec);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edycja");

        mEdytuj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mEdytuj.setText("Edytuj");
        mEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEdytujActionPerformed(evt);
            }
        });
        jMenu2.add(mEdytuj);

        mUsun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mUsun.setText("Usuń");
        mUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsunActionPerformed(evt);
            }
        });
        jMenu2.add(mUsun);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bNowy)
                        .addGap(36, 36, 36)
                        .addComponent(bZapisz)
                        .addGap(50, 50, 50)
                        .addComponent(bEdytuj)
                        .addGap(40, 40, 40)
                        .addComponent(bUsun))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel3)
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel2))
                                                        .addComponent(jLabel4))
                                                    .addComponent(jLabel5))
                                                .addComponent(jLabel6))
                                            .addComponent(jLabel7))
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel9))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tDataZakonczenia, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(tDataRozpoczecia)
                            .addComponent(tStanowisko)
                            .addComponent(tUlica)
                            .addComponent(tKodpocztowy)
                            .addComponent(tMiejscowosc)
                            .addComponent(tNumerTelefonu)
                            .addComponent(tNrPracownika)
                            .addComponent(tImie)
                            .addComponent(tNazwisko)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(pracownicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pracownicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tNrPracownika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNumerTelefonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tKodpocztowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tStanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tDataRozpoczecia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tDataZakonczenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNowy)
                    .addComponent(bEdytuj)
                    .addComponent(bUsun)
                    .addComponent(bZapisz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pracownicyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracownicyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pracownicyComboBoxActionPerformed

    private void bNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNowyActionPerformed
        // TODO add your handling code here:
        this.odblokujTekst();
        this.bNowy.setEnabled(false);
        this.bZapisz.setEnabled(true);
        this.bEdytuj.setEnabled(false);
        this.bUsun.setEnabled(false);
        pracownicyComboBox.setEnabled(false);
        tNrPracownika.setText("");
        tImie.setText("");
        tNazwisko.setText("");
        tNumerTelefonu.setText("");
        tMiejscowosc.setText("");
        tKodpocztowy.setText("");
        tUlica.setText("");
        tStanowisko.setText("");
        tDataRozpoczecia.setText("");        
        tDataZakonczenia.setText("");
    }//GEN-LAST:event_bNowyActionPerformed

    private void bZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZapiszActionPerformed
        // TODO add your handling code here:
        if(tNrPracownika.isEnabled()){
            bd.zapis(tNrPracownika.getText(),
        tImie.getText(),
        tNazwisko.getText(),
        tNumerTelefonu.getText(),
        tMiejscowosc.getText(),
        tKodpocztowy.getText(),
        tUlica.getText(),
        tStanowisko.getText(),
        tDataRozpoczecia.getText(),        
        tDataZakonczenia.getText());
        } else if(!tNrPracownika.isEnabled()){
            bd.modyfikuj(tNrPracownika.getText(),
        tImie.getText(),
        tNazwisko.getText(),
        tNumerTelefonu.getText(),
        tMiejscowosc.getText(),
        tKodpocztowy.getText(),
        tUlica.getText(),
        tStanowisko.getText(),
        tDataRozpoczecia.getText(),        
        tDataZakonczenia.getText());
        }
        
        this.zablokujTekst();
        this.bNowy.setEnabled(true);
        this.bZapisz.setEnabled(false);
        this.bEdytuj.setEnabled(true);
        this.bUsun.setEnabled(true);
        pracownicyComboBox.setEnabled(true);
        dane = bd.odczyt();
        pracownicyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        pracownicyComboBox.setSelectedItem(tNrPracownika.getText());
    }//GEN-LAST:event_bZapiszActionPerformed

    private void bEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEdytujActionPerformed
        // TODO add your handling code here:
        this.odblokujTekst();
        pracownicyComboBox.setEnabled(false);
        this.tNrPracownika.setEnabled(false);
        this.bZapisz.setEnabled(true);
        this.bNowy.setEnabled(false);
        this.bUsun.setEnabled(false);
        this.bEdytuj.setEnabled(false);
    }//GEN-LAST:event_bEdytujActionPerformed

    private void bUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsunActionPerformed
        // TODO add your handling code here:
        bd.usun(tNrPracownika.getText());
        dane = bd.odczyt();
        pracownicyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        pracownicyComboBox.setSelectedItem(String.valueOf(dane.get(0).getNrPracownika()));
    }//GEN-LAST:event_bUsunActionPerformed

    private void mNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNowyActionPerformed
        // TODO add your handling code here:
        this.bNowyActionPerformed(evt);
    }//GEN-LAST:event_mNowyActionPerformed

    private void mZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mZapiszActionPerformed
        // TODO add your handling code here:
        this.bZapiszActionPerformed(evt);
    }//GEN-LAST:event_mZapiszActionPerformed

    private void mKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKoniecActionPerformed
        // TODO add your handling code here:
        dispose();
        setVisible(false);
    }//GEN-LAST:event_mKoniecActionPerformed

    private void mEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEdytujActionPerformed
        // TODO add your handling code here:
        this.bEdytujActionPerformed(evt);
    }//GEN-LAST:event_mEdytujActionPerformed

    private void mUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsunActionPerformed
        // TODO add your handling code here:
        this.bUsunActionPerformed(evt);
    }//GEN-LAST:event_mUsunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracownikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracownikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracownikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracownikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracownikFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdytuj;
    private javax.swing.JButton bNowy;
    private javax.swing.JButton bUsun;
    private javax.swing.JButton bZapisz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mEdytuj;
    private javax.swing.JMenuItem mKoniec;
    private javax.swing.JMenuItem mNowy;
    private javax.swing.JMenuItem mUsun;
    private javax.swing.JMenuItem mZapisz;
    private javax.swing.JComboBox<String> pracownicyComboBox;
    private javax.swing.JTextField tDataRozpoczecia;
    private javax.swing.JTextField tDataZakonczenia;
    private javax.swing.JTextField tImie;
    private javax.swing.JTextField tKodpocztowy;
    private javax.swing.JTextField tMiejscowosc;
    private javax.swing.JTextField tNazwisko;
    private javax.swing.JTextField tNrPracownika;
    private javax.swing.JTextField tNumerTelefonu;
    private javax.swing.JTextField tStanowisko;
    private javax.swing.JTextField tUlica;
    // End of variables declaration//GEN-END:variables
    private BazaPracownik bd;
    private ArrayList<Pracownik> dane;
    private int i;
}
