/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import javax.swing.ImageIcon;

/**
 *
 * @author Piotr Buczek
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        ImagePanel panel = new ImagePanel(
        new ImageIcon("images/bg.jpg").getImage());
        getContentPane().add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPracownicy = new javax.swing.JButton();
        bKarty = new javax.swing.JButton();
        bWydatki = new javax.swing.JButton();
        bSprzet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mPracownicy = new javax.swing.JMenuItem();
        mKart = new javax.swing.JMenuItem();
        mWydatki = new javax.swing.JMenuItem();
        mSprzet = new javax.swing.JMenuItem();
        mWyloguj = new javax.swing.JMenuItem();
        mKoniec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System zarządzania biurem");

        bPracownicy.setText("Zarządzaj pracownikami");
        bPracownicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPracownicyActionPerformed(evt);
            }
        });

        bKarty.setText("Zarządzaj kartami dostępowymi");
        bKarty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKartyActionPerformed(evt);
            }
        });

        bWydatki.setText("Zarządzaj wydatkami");
        bWydatki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWydatkiActionPerformed(evt);
            }
        });

        bSprzet.setText("Zarządzaj wypożyczonym sprzętem");
        bSprzet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSprzetActionPerformed(evt);
            }
        });

        jButton1.setText("Wyloguj się");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Plik");

        mPracownicy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mPracownicy.setText("Zarządzaj pracownikami");
        mPracownicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPracownicyActionPerformed(evt);
            }
        });
        jMenu1.add(mPracownicy);

        mKart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mKart.setText("Zarządzaj kartami");
        mKart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKartActionPerformed(evt);
            }
        });
        jMenu1.add(mKart);

        mWydatki.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mWydatki.setText("Zarządzaj wydatkami");
        mWydatki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mWydatkiActionPerformed(evt);
            }
        });
        jMenu1.add(mWydatki);

        mSprzet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mSprzet.setText("Zarządzaj sprzętem");
        mSprzet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSprzetActionPerformed(evt);
            }
        });
        jMenu1.add(mSprzet);

        mWyloguj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mWyloguj.setText("Wyloguj się");
        mWyloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mWylogujActionPerformed(evt);
            }
        });
        jMenu1.add(mWyloguj);

        mKoniec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mKoniec.setText("Koniec");
        mKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKoniecActionPerformed(evt);
            }
        });
        jMenu1.add(mKoniec);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(bKarty)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(bPracownicy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(bWydatki, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(bSprzet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(bPracownicy)
                .addGap(18, 18, 18)
                .addComponent(bKarty)
                .addGap(18, 18, 18)
                .addComponent(bWydatki)
                .addGap(18, 18, 18)
                .addComponent(bSprzet)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPracownicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPracownicyActionPerformed
        // TODO add your handling code here:
        PracownikFrame pf = new PracownikFrame();
        pf.setVisible(true);
    }//GEN-LAST:event_bPracownicyActionPerformed

    private void bKartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKartyActionPerformed
        // TODO add your handling code here:
        KartyDostepoweFrame kf = new KartyDostepoweFrame();
        kf.setVisible(true);
    }//GEN-LAST:event_bKartyActionPerformed

    private void bWydatkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWydatkiActionPerformed
        // TODO add your handling code here:
        WydatkiFrame wf = new WydatkiFrame();
        wf.setVisible(true);
    }//GEN-LAST:event_bWydatkiActionPerformed

    private void bSprzetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSprzetActionPerformed
        // TODO add your handling code here:
        WypozyczonySprzetFrame wf = new WypozyczonySprzetFrame();
        wf.setVisible(true);
    }//GEN-LAST:event_bSprzetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.Window win[] = java.awt.Window.getWindows();
        for(int i=0;i<win.length;i++){
            win[i].dispose();
        }
        LogowanieFrame lf = new LogowanieFrame();
        lf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mPracownicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPracownicyActionPerformed
        // TODO add your handling code here:
        this.bPracownicyActionPerformed(evt);
    }//GEN-LAST:event_mPracownicyActionPerformed

    private void mKartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKartActionPerformed
        // TODO add your handling code here:
        this.bKartyActionPerformed(evt);
    }//GEN-LAST:event_mKartActionPerformed

    private void mWydatkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mWydatkiActionPerformed
        // TODO add your handling code here:
        this.bWydatkiActionPerformed(evt);
    }//GEN-LAST:event_mWydatkiActionPerformed

    private void mSprzetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSprzetActionPerformed
        // TODO add your handling code here:
        this.bSprzetActionPerformed(evt);
    }//GEN-LAST:event_mSprzetActionPerformed

    private void mWylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mWylogujActionPerformed
        // TODO add your handling code here:
        this.jButton1ActionPerformed(evt);
    }//GEN-LAST:event_mWylogujActionPerformed

    private void mKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKoniecActionPerformed
        // TODO add your handling code here:
        java.awt.Window win[] = java.awt.Window.getWindows();
        for(int i=0;i<win.length;i++){
            win[i].dispose();
        }
        setVisible(false);
    }//GEN-LAST:event_mKoniecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKarty;
    private javax.swing.JButton bPracownicy;
    private javax.swing.JButton bSprzet;
    private javax.swing.JButton bWydatki;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mKart;
    private javax.swing.JMenuItem mKoniec;
    private javax.swing.JMenuItem mPracownicy;
    private javax.swing.JMenuItem mSprzet;
    private javax.swing.JMenuItem mWydatki;
    private javax.swing.JMenuItem mWyloguj;
    // End of variables declaration//GEN-END:variables
}
