/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.BazaKarta;
import backend.BazaWydatek;
import backend.Wydatek;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Piotr Buczek
 */
public class WydatkiFrame extends javax.swing.JFrame {

    /**
     * Creates new form WydatkiFrame
     */
    public WydatkiFrame() {
        initComponents();
        this.zablokujTekst();
        bd = new BazaWydatek();
        dane = bd.odczyt();
        pf = new PracownikFrame();
        wydatkiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        wydatkiComboBox.addActionListener(new ActionListener() {
 
        @Override
        public void actionPerformed(ActionEvent event) {
        JComboBox<String> combo = (JComboBox<String>) event.getSource();
        String selectedWydatek = (String) combo.getSelectedItem();
 
        wyswietlWydatek(Integer.parseInt(selectedWydatek));
            }
        });
        
        this.bZapisz.setEnabled(false);
        this.wyswietl(0);
        this.setTitle("Menedżer wydatków");
    }
    
    private void wyswietl(int i){
        Wydatek w = dane.get(i);
        tNrWydatku.setText(""+w.getNrWydatku());
        tPrzedmiot.setText(w.getPrzedmiot());
        tDataKupna.setText(w.getDataKupna());
        tKoszt.setText(""+w.getKoszt());
        tNrPracownika.setText(""+w.getNrPracownika());
        tBudzet.setText(String.valueOf(obliczBudzet(totalBudzet)));
    }
    
    private void wyswietlWydatek(int nrWydatku){
        for(int i=0;i<dane.size();i++){
            if(((Wydatek)dane.get(i)).getNrWydatku()==nrWydatku){
                this.i = i;
                wyswietl(i);
            }
        }
    }
    
    private String[] initializeComboBox(ArrayList<Wydatek> wydatki){
        String[] numbers = new String[wydatki.size()];
        int i = 0;
        for(Wydatek wydatek : wydatki){
            numbers[i] = String.valueOf(wydatek.getNrWydatku());
            i++;
        }
        return numbers;
    }
    
    private double obliczBudzet(double totalBudzet){
        double aktualnyBudzet = totalBudzet;
        for(int i=0;i<dane.size();i++){
            aktualnyBudzet -= dane.get(i).getKoszt();
        }
        return aktualnyBudzet;
    }
    
    private void odblokujTekst(){
        tPrzedmiot.setEnabled(true);
        tDataKupna.setEnabled(true);
        tKoszt.setEnabled(true);
        tNrPracownika.setEnabled(true);
    }
    
    private void zablokujTekst(){
        tNrWydatku.setEnabled(false);
        tPrzedmiot.setEnabled(false);
        tDataKupna.setEnabled(false);
        tKoszt.setEnabled(false);
        tNrPracownika.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        wydatkiComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNrWydatku = new javax.swing.JTextField();
        tPrzedmiot = new javax.swing.JTextField();
        tDataKupna = new javax.swing.JTextField();
        tKoszt = new javax.swing.JTextField();
        tNrPracownika = new javax.swing.JTextField();
        bNowy = new javax.swing.JButton();
        bZapisz = new javax.swing.JButton();
        bEdytuj = new javax.swing.JButton();
        bUsun = new javax.swing.JButton();
        bWyswietl = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tBudzet = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mNowy = new javax.swing.JMenuItem();
        mZapisz = new javax.swing.JMenuItem();
        mKoniec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mEdytuj = new javax.swing.JMenuItem();
        mUsun = new javax.swing.JMenuItem();

        jLabel1.setText("Wybierz numer wydatku:");

        wydatkiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Numer wydatku:");

        jLabel3.setText("Przedmiot:");

        jLabel4.setText("Data kupna:");

        jLabel5.setText("Koszt:");

        jLabel6.setText("Numer pracownika:");

        tNrWydatku.setText("jTextField1");

        tPrzedmiot.setText("jTextField2");

        tDataKupna.setText("jTextField3");

        tKoszt.setText("jTextField4");

        tNrPracownika.setText("jTextField5");

        bNowy.setText("Nowy");
        bNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNowyActionPerformed(evt);
            }
        });

        bZapisz.setText("Zapisz");
        bZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZapiszActionPerformed(evt);
            }
        });

        bEdytuj.setText("Edycja");
        bEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEdytujActionPerformed(evt);
            }
        });

        bUsun.setText("Usuń");
        bUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsunActionPerformed(evt);
            }
        });

        bWyswietl.setText("Wyświetl dane o pracowniku");
        bWyswietl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWyswietlActionPerformed(evt);
            }
        });

        jLabel7.setText("Pozostały budżet:");

        tBudzet.setForeground(new java.awt.Color(255, 0, 0));
        tBudzet.setText("jLabel8");

        jMenu1.setText("Plik");

        mNowy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNowy.setText("Nowy");
        mNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNowyActionPerformed(evt);
            }
        });
        jMenu1.add(mNowy);

        mZapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mZapisz.setText("Zapisz");
        mZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mZapiszActionPerformed(evt);
            }
        });
        jMenu1.add(mZapisz);

        mKoniec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mKoniec.setText("Koniec");
        mKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKoniecActionPerformed(evt);
            }
        });
        jMenu1.add(mKoniec);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edycja");

        mEdytuj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mEdytuj.setText("Edytuj");
        mEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEdytujActionPerformed(evt);
            }
        });
        jMenu2.add(mEdytuj);

        mUsun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mUsun.setText("Usun");
        mUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsunActionPerformed(evt);
            }
        });
        jMenu2.add(mUsun);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(wydatkiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(tNrWydatku, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tKoszt)
                                    .addComponent(tNrPracownika)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66)
                                .addComponent(tDataKupna))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(73, 73, 73)
                                .addComponent(tPrzedmiot)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tBudzet)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bWyswietl)))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bNowy)
                .addGap(18, 18, 18)
                .addComponent(bZapisz)
                .addGap(18, 18, 18)
                .addComponent(bEdytuj)
                .addGap(18, 18, 18)
                .addComponent(bUsun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wydatkiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tNrWydatku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tBudzet)
                    .addComponent(tPrzedmiot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tDataKupna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tKoszt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tNrPracownika)
                    .addComponent(bWyswietl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNowy)
                    .addComponent(bZapisz)
                    .addComponent(bEdytuj)
                    .addComponent(bUsun))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNowyActionPerformed
        // TODO add your handling code here:
        this.odblokujTekst();
        this.bNowy.setEnabled(false);
        this.bZapisz.setEnabled(true);
        this.bEdytuj.setEnabled(false);
        this.bUsun.setEnabled(false);
         this.bWyswietl.setEnabled(false);
        this.wydatkiComboBox.setEnabled(false);

//         int nastepnyNumerWydatku = dane.get(dane.size()-1).getNrWydatku()+1;
        tNrWydatku.setText("Generowany automatycznie");       
        tPrzedmiot.setText("");
        tDataKupna.setText("");
        tKoszt.setText("");
        tNrPracownika.setText("");

    }//GEN-LAST:event_bNowyActionPerformed

    private void bZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZapiszActionPerformed
        // TODO add your handling code here:
//        dane.get(i).getNrWydatku() != Integer.parseInt(tNrWydatku.getText())
        if(tNrWydatku.getText().equals("Generowany automatycznie")){
            bd.zapis(tPrzedmiot.getText(),
        tDataKupna.getText(),
        tKoszt.getText(),
        tNrPracownika.getText());
        } else if(dane.get(i).getNrWydatku() == Integer.parseInt(tNrWydatku.getText())){
            bd.modyfikuj(tNrWydatku.getText(),
                    tPrzedmiot.getText(),
        tDataKupna.getText(),
        tKoszt.getText(),
        tNrPracownika.getText());
        }
        
        
        this.zablokujTekst();
        this.bNowy.setEnabled(true);
        this.bZapisz.setEnabled(false);
        this.bEdytuj.setEnabled(true);
        this.bUsun.setEnabled(true);
        this.bWyswietl.setEnabled(true);
        wydatkiComboBox.setEnabled(true);
        dane = bd.odczyt();
        wydatkiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        wydatkiComboBox.setSelectedItem(String.valueOf(dane.get(dane.size()-1).getNrWydatku()));
    }//GEN-LAST:event_bZapiszActionPerformed

    private void bEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEdytujActionPerformed
        // TODO add your handling code here:
        this.odblokujTekst();
        this.wydatkiComboBox.setEnabled(false);
        this.bZapisz.setEnabled(true);
        this.bNowy.setEnabled(false);
        this.bUsun.setEnabled(false);
        this.bEdytuj.setEnabled(false);
    }//GEN-LAST:event_bEdytujActionPerformed

    private void bUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsunActionPerformed
        // TODO add your handling code here:
        bd.usun(tNrWydatku.getText());
        dane = bd.odczyt();
        wydatkiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(initializeComboBox(dane)));
        wydatkiComboBox.setSelectedItem(String.valueOf(dane.get(0).getNrWydatku()));
    }//GEN-LAST:event_bUsunActionPerformed

    private void bWyswietlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWyswietlActionPerformed
        // TODO add your handling code here:
        pf.wyswietlPracownika(Long.parseLong(tNrPracownika.getText()));
        pf.setVisible(true);
    }//GEN-LAST:event_bWyswietlActionPerformed

    private void mZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mZapiszActionPerformed
        // TODO add your handling code here:
        this.bZapiszActionPerformed(evt);
    }//GEN-LAST:event_mZapiszActionPerformed

    private void mNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNowyActionPerformed
        // TODO add your handling code here:
        this.bNowyActionPerformed(evt);
    }//GEN-LAST:event_mNowyActionPerformed

    private void mKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKoniecActionPerformed
        // TODO add your handling code here:
        dispose();
        setVisible(false);
    }//GEN-LAST:event_mKoniecActionPerformed

    private void mEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEdytujActionPerformed
        // TODO add your handling code here:
        this.bEdytujActionPerformed(evt);
    }//GEN-LAST:event_mEdytujActionPerformed

    private void mUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsunActionPerformed
        // TODO add your handling code here:
        this.bUsunActionPerformed(evt);
    }//GEN-LAST:event_mUsunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WydatkiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WydatkiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WydatkiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WydatkiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WydatkiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdytuj;
    private javax.swing.JButton bNowy;
    private javax.swing.JButton bUsun;
    private javax.swing.JButton bWyswietl;
    private javax.swing.JButton bZapisz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mEdytuj;
    private javax.swing.JMenuItem mKoniec;
    private javax.swing.JMenuItem mNowy;
    private javax.swing.JMenuItem mUsun;
    private javax.swing.JMenuItem mZapisz;
    private javax.swing.JLabel tBudzet;
    private javax.swing.JTextField tDataKupna;
    private javax.swing.JTextField tKoszt;
    private javax.swing.JTextField tNrPracownika;
    private javax.swing.JTextField tNrWydatku;
    private javax.swing.JTextField tPrzedmiot;
    private javax.swing.JComboBox<String> wydatkiComboBox;
    // End of variables declaration//GEN-END:variables
    private BazaWydatek bd;
    private ArrayList<Wydatek> dane;
    private int i;
    private PracownikFrame pf;
    private double totalBudzet = 10000;
}
